namespace: masterit_dev
name: pasteque
version: 1.1.1
readme: README.md
authors:
  - MasterIT | Lucien DURAND-HARDY <lucien.durandhardy@masterit.fr>
description: A collection for pasteque API and JSAdmin interface
license:
  - CC-BY-SA-4.0
tags:
  - pasteque
  - cashregister
  - caisses

dependencies: {}

repository: https://github.com/masterit-dev/ansible-collection-pasteque.git
documentation: https://github.com/masterit-dev/ansible-collection-pasteque.git
homepage: https://github.com/masterit-dev/ansible-collection-pasteque.git
issues: https://github.com/masterit-dev/ansible-collection-pasteque/issues

build_ignore: []

